"""add_product_experience_reports

Revision ID: 38caf4419f59
Revises: f4a8c2e9d5b7
Create Date: 2026-04-24 03:23:05.537806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38caf4419f59'
down_revision: Union[str, None] = 'f4a8c2e9d5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_experience_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_slug', sa.String(length=64), nullable=False),
    sa.Column('product_url', sa.Text(), nullable=False),
    sa.Column('product_name', sa.String(length=256), nullable=False),
    sa.Column('run_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('login_used', sa.String(length=16), nullable=False),
    sa.Column('overall_ux_score', sa.Float(), nullable=True),
    sa.Column('summary_zh', sa.Text(), nullable=True),
    sa.Column('feature_inventory', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('monetization_model', sa.Text(), nullable=True),
    sa.Column('target_user', sa.Text(), nullable=True),
    sa.Column('screenshots', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agent_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_experience_reports_product_slug'), 'product_experience_reports', ['product_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_experience_reports_product_slug'), table_name='product_experience_reports')
    op.drop_table('product_experience_reports')
    # ### end Alembic commands ###
