"""add item insights fields

Revision ID: b9ba9e1280e4
Revises: 425b560aeb5f
Create Date: 2026-04-15 09:49:38.117259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9ba9e1280e4'
down_revision: Union[str, None] = '425b560aeb5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_items', sa.Column('summary_zh', sa.Text(), nullable=True))
    op.add_column('source_items', sa.Column('problem', sa.Text(), nullable=True))
    op.add_column('source_items', sa.Column('opportunity', sa.Text(), nullable=True))
    op.add_column('source_items', sa.Column('target_user', sa.Text(), nullable=True))
    op.add_column('source_items', sa.Column('why_now', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_items', 'why_now')
    op.drop_column('source_items', 'target_user')
    op.drop_column('source_items', 'opportunity')
    op.drop_column('source_items', 'problem')
    op.drop_column('source_items', 'summary_zh')
    # ### end Alembic commands ###
